import type { MaterialKind, Provenance, QuizQuestion, RubricCriterion } from './api'
import { gradeLabel, learners, lessonMinutes, levelOf, type Level } from './levels'
import { blocksToHtml, parseBlocks, stripInline } from './markdown'

// Template-driven stand-in for the on-device model. Two curated content packs
// cover the demo classes; any other topic falls back to a generic pack.

export type Mode = 'lesson' | 'rubric' | 'remedial' | 'quiz'
export type Tier = 'standard' | 'remedial' | 'honors'
export type ExportFormat = 'pdf' | 'markdown' | 'csv'
export type Refinement = 'review' | 'simplify' | 'bilingual'

export const MODES: Record<Mode, { label: string; description: string }> = {
  lesson: { label: 'Lesson Plan', description: 'Objectives, warm-up, core activity, exit ticket' },
  rubric: { label: 'Rubric Builder', description: 'Criteria and 4-level performance descriptors' },
  remedial: { label: 'Remedial Worksheet', description: 'Scaffolded recall and guided practice' },
  quiz: { label: 'Quiz Generator', description: 'Multiple-choice items with answer key' },
}

export const TIERS: Record<Tier, { label: string; description: string }> = {
  standard: { label: 'Standard', description: 'On-level pacing and grade-level vocabulary' },
  remedial: { label: 'Simplified for Remedial', description: 'Shorter steps, word banks and sentence starters' },
  honors: { label: 'Advanced Honors', description: 'Extension tasks, data analysis and open inquiry' },
}

export const FORMATS: Record<ExportFormat, { label: string; description: string; ext: string; mime: string }> = {
  pdf: { label: 'PDF Handout', description: 'Print-ready handout, saved via the print dialog', ext: 'pdf', mime: 'application/pdf' },
  markdown: { label: 'Markdown', description: 'Editable .md for notes, docs and wikis', ext: 'md', mime: 'text/markdown' },
  csv: { label: 'LMS CSV sync', description: 'One row per item for LMS import', ext: 'csv', mime: 'text/csv' },
}

export interface DraftSection {
  id: string
  title: string
  body: string
  /** Rendered from structured quiz/rubric data; edited through those fields, not as text. */
  readonly?: boolean
}

export interface DraftParams {
  topic: string
  subject: string
  /** Missing on drafts saved before levels existed; read it through levelOf(). */
  level?: Level
  grade: number
  mode: Mode
  tier: Tier
  format: ExportFormat
  /** One learning objective per line (the backend requires at least one). */
  objectives: string
}

/** Server-side state of a draft generated by the backend (POST /materials/generate). */
export interface MaterialMeta {
  id: string
  kind: MaterialKind
  revision: number
  status: 'draft' | 'reviewed'
  provenance: Provenance
  quiz: QuizQuestion[]
  rubric: RubricCriterion[]
}

export interface Draft extends DraftParams {
  id: string
  title: string
  minutes: number
  sections: DraftSection[]
  refinements: Refinement[]
  createdISO: string
  /** template: built on the device (demo). gemini: generated and stored by the backend. */
  origin: 'template' | 'gemini'
  material?: MaterialMeta
  /** Local edits not yet saved to the backend. */
  dirty?: boolean
}

interface QuizItem {
  q: string
  choices: string[]
  answer: number
}

interface Pack {
  topicTl: string
  task: string
  objectives: [string, string, string]
  hook: string
  activities: [string, string, string]
  keyTerms: string[]
  extension: string
  exit: [string, string]
  review: [string, string, string]
  quiz: QuizItem[]
  criteria: [string, string][]
}

const PHOTO: Pack = {
  topicTl: 'potosintesis at respirasyong selular',
  task: 'Leaf-disk photosynthesis lab report',
  objectives: [
    'Explain how photosynthesis converts light energy into chemical energy stored in glucose',
    'Compare the reactants and products of photosynthesis and cellular respiration',
    'Demonstrate how the two processes form a continuous energy cycle',
  ],
  hook: 'Display a photo of a leaf next to a runner and ask: *Where does each one get its energy?*',
  activities: [
    'Station A: Utilize the leaf-disk float test to observe oxygen production under light and shade',
    'Station B: Sort equation cards (CO₂, H₂O, C₆H₁₂O₆, O₂, ATP) into the correct process',
    'Station C: Construct a Venn diagram comparing chloroplasts and mitochondria',
  ],
  keyTerms: ['chlorophyll', 'glucose', 'mitochondria', 'stomata', 'ATP'],
  extension: 'Analyze a graph of CO₂ uptake versus light intensity and identify the limiting factor',
  exit: [
    'In two sentences, explain why plants need both photosynthesis and cellular respiration',
    'Name the organelle where each process takes place',
  ],
  review: [
    'What are the reactants and products of photosynthesis?',
    'Where in the cell does cellular respiration take place?',
    'How is the oxygen released by plants utilized by animals?',
  ],
  quiz: [
    { q: 'Which organelle is the site of photosynthesis?', choices: ['Mitochondrion', 'Chloroplast', 'Ribosome', 'Nucleus'], answer: 1 },
    { q: 'Which gas do plants absorb for photosynthesis?', choices: ['Oxygen', 'Nitrogen', 'Carbon dioxide', 'Hydrogen'], answer: 2 },
    { q: 'Cellular respiration releases usable energy in the form of…', choices: ['ATP', 'Chlorophyll', 'Starch', 'Water'], answer: 0 },
    { q: 'Which pigment absorbs light energy in leaves?', choices: ['Hemoglobin', 'Chlorophyll', 'Melanin', 'Keratin'], answer: 1 },
    { q: 'The Calvin cycle produces…', choices: ['Oxygen', 'Water', 'Glucose', 'ATP only'], answer: 2 },
    { q: 'Which pair are both products of cellular respiration?', choices: ['Glucose and oxygen', 'Carbon dioxide and water', 'Chlorophyll and ATP', 'Starch and oxygen'], answer: 1 },
  ],
  criteria: [
    ['Hypothesis & variables', 'States a testable hypothesis about light and photosynthesis rate, naming the independent and dependent variables'],
    ['Data collection', 'Records leaf-disk float times in a labeled table with units across at least three trials'],
    ['Analysis', 'Utilizes the data to explain how light intensity affects oxygen production'],
    ['Communication', 'Presents a clear conclusion that connects photosynthesis and cellular respiration'],
  ],
}

const STOICH: Pack = {
  topicTl: 'stoichiometry (ugnayan ng dami ng reaktant at produkto)',
  task: 'Stoichiometry problem set',
  objectives: [
    'Explain how the mole connects particle counts to measurable mass',
    'Utilize mole ratios from a balanced equation to predict product amounts',
    'Determine the limiting reactant in a chemical reaction',
  ],
  hook: 'Show a recipe that makes 12 pancakes and ask: *How many eggs do you need for 36?*',
  activities: [
    'Station A: Balance 2H₂ + O₂ → 2H₂O and identify each mole ratio',
    'Station B: Utilize molar masses to convert 10.0 g of H₂ into moles',
    'Station C: Determine the limiting reactant when 4 mol H₂ reacts with 1 mol O₂',
  ],
  keyTerms: ['mole', 'molar mass', 'mole ratio', 'limiting reactant', 'theoretical yield'],
  extension: 'Calculate the percent yield when a lab produces 15.2 g of water from 2.0 g of H₂',
  exit: ['How many moles of H₂O form from 3 mol of O₂?', 'Explain in one sentence what a limiting reactant is'],
  review: [
    'What is the molar mass of H₂O?',
    'How many particles are in one mole of a substance?',
    'What does a mole ratio tell you about a reaction?',
  ],
  quiz: [
    { q: 'How many moles of O₂ react with 4 mol of H₂ in 2H₂ + O₂ → 2H₂O?', choices: ['1 mol', '2 mol', '4 mol', '8 mol'], answer: 1 },
    { q: 'What is the molar mass of H₂O?', choices: ['16 g/mol', '17 g/mol', '18 g/mol', '20 g/mol'], answer: 2 },
    { q: 'One mole of any substance contains how many particles?', choices: ['6.022 × 10²³', '3.14 × 10²³', '6.022 × 10²²', '1.0 × 10²³'], answer: 0 },
    { q: 'The reactant that is used up first is called the…', choices: ['Excess reactant', 'Catalyst', 'Limiting reactant', 'Product'], answer: 2 },
    { q: 'How many grams are in 2.0 mol of CO₂ (44 g/mol)?', choices: ['22 g', '44 g', '66 g', '88 g'], answer: 3 },
    { q: 'The coefficients of a balanced equation show ratios of…', choices: ['Masses', 'Moles', 'Volumes only', 'Densities'], answer: 1 },
  ],
  criteria: [
    ['Balanced equation', 'Balances the chemical equation and identifies every mole ratio'],
    ['Unit conversions', 'Converts between grams, moles and particles with correct units'],
    ['Limiting reactant', 'Determines the limiting reactant and justifies the choice'],
    ['Communication', 'Shows organized, labeled solutions that a classmate can follow'],
  ],
}

function genericPack(topic: string): Pack {
  const t = topic.trim() || 'the topic'
  return {
    topicTl: t,
    task: `${t} performance task`,
    objectives: [
      `Explain the central ideas of ${t}`,
      `Illustrate how ${t} connects to everyday experiences`,
      `Utilize key vocabulary to describe ${t} accurately`,
    ],
    hook: `Pose a real-world question about ${t} and ask: *What do you already know?*`,
    activities: [
      `Station A: Read a short passage on ${t} and annotate three key ideas`,
      `Station B: Construct a concept map that links the main terms of ${t}`,
      'Station C: Apply the concept to a new example and present your reasoning to another group',
    ],
    keyTerms: [],
    extension: `Design a short investigation that tests one claim about ${t}`,
    exit: [`Summarize ${t} in two sentences`, `Write one question you still have about ${t}`],
    review: [
      `What is the most important idea you learned about ${t}?`,
      `How would you explain ${t} to a younger student?`,
      `Give one real-life example of ${t}.`,
    ],
    quiz: [],
    criteria: [
      ['Understanding', `Accurately explains the key ideas of ${t}`],
      ['Application', 'Applies the concept correctly to a new example'],
      ['Evidence', 'Supports claims with data, observations or text references'],
      ['Communication', 'Organizes ideas clearly using subject vocabulary'],
    ],
  }
}

function packFor(topic: string): Pack {
  if (/photosynth|respiration|chloroplast/i.test(topic)) return PHOTO
  if (/stoich|mole/i.test(topic)) return STOICH
  return genericPack(topic)
}

const LETTER = ['A', 'B', 'C', 'D']

function capitalizeFirst(text: string): string {
  return text.charAt(0).toUpperCase() + text.slice(1)
}

function lessonSections(p: Pack, d: DraftParams, minutes: number): DraftSection[] {
  const core = minutes - 15
  const exitMin = minutes >= 60 ? 10 : 5
  const objectives =
    d.tier === 'remedial'
      ? [`With guided support, ${p.objectives[0].charAt(0).toLowerCase()}${p.objectives[0].slice(1)}`, p.objectives[1]]
      : d.tier === 'honors'
        ? [...p.objectives, 'Analyze evidence to evaluate and justify scientific conclusions']
        : p.objectives
  const warmup = [
    '**5 min** · Whole class',
    `- ${p.hook}`,
    '- Learners write a one-sentence prediction, then share with a partner',
    '- Subsequently, record three ideas on the board to revisit during the exit ticket',
  ]
  if (d.tier === 'remedial') warmup.push('- Provide the sentence starter: *I think … because …*')
  const coreLines = [`**${core} min** · Groups of 4, station rotation`, ...p.activities.map((a, i) => `${i + 1}. ${a}`)]
  coreLines.push('- Facilitate a 5-minute gallery walk so groups can compare their work')
  if (d.tier === 'remedial') {
    if (p.keyTerms.length) coreLines.push(`- **Word bank:** ${p.keyTerms.join(', ')}`)
    coreLines.push('- Give each group a step-by-step checklist for every station')
  }
  if (d.tier === 'honors') coreLines.push(`- **Extension:** ${p.extension}`)
  return [
    {
      id: 'objective',
      title: 'Objective',
      body: `By the end of this ${minutes}-minute session, ${learners(levelOf(d), d.grade)} will be able to:\n${objectives.map((o) => `- ${o}`).join('\n')}`,
    },
    { id: 'warmup', title: 'Warm-up', body: warmup.join('\n') },
    { id: 'core', title: 'Core Activity', body: coreLines.join('\n') },
    {
      id: 'exit',
      title: 'Exit Ticket',
      body: [`**${exitMin} min** · Individual`, `- ${p.exit[0]}`, `- ${p.exit[1]}`, '- Rate your confidence from 1 to 4'].join('\n'),
    },
  ]
}

function remedialSections(p: Pack, d: DraftParams): DraftSection[] {
  const recall = p.keyTerms.length
    ? `- Match each term to its meaning: ${p.keyTerms.join(', ')}`
    : `- List three words you remember about ${d.topic}`
  const practice = [
    '1. Read the worked example together and underline each step',
    `2. ${p.activities[1].replace(/^Station [A-C]: /, '')}`,
    '3. Complete two practice items with a partner, then one on your own',
    '- **Sentence starter:** *The answer is … because …*',
  ]
  if (d.tier === 'honors') practice.push(`- **Challenge:** ${p.extension}`)
  return [
    {
      id: 'objective',
      title: 'Objective',
      body: `${capitalizeFirst(learners(levelOf(d), d.grade))} who need extra support will be able to:\n- ${p.objectives[0]}\n- Utilize key vocabulary accurately in complete sentences`,
    },
    { id: 'warmup', title: 'Recall Warm-up', body: `${recall}\n- Circle the term you find most difficult` },
    { id: 'guided', title: 'Guided Practice', body: practice.join('\n') },
    { id: 'exit', title: 'Exit Ticket', body: `- ${p.exit[0]}\n- Draw a face that shows how confident you feel` },
  ]
}

function quizSections(p: Pack, d: DraftParams): DraftSection[] {
  const count = d.tier === 'remedial' ? 4 : d.tier === 'honors' ? 6 : 5
  const time = d.tier === 'remedial' ? 15 : d.tier === 'honors' ? 25 : 20
  const items = p.quiz.slice(0, count)
  let questions: string
  let key: string
  let numbered = items.length
  if (items.length) {
    questions = items
      .map((it, i) => `${i + 1}. ${it.q}\n  ${it.choices.map((c, ci) => `${LETTER[ci]}. ${c}`).join('   ')}`)
      .join('\n')
    key = items.map((it, i) => `${i + 1}. ${LETTER[it.answer]} · ${it.choices[it.answer]}`).join('\n')
  } else {
    const prompts = [...p.review, p.exit[0]].slice(0, count)
    numbered = prompts.length
    questions = prompts.map((q, i) => `${i + 1}. ${q}\n  *Short answer*`).join('\n')
    key = `- Answers will vary. Accept responses that ${p.objectives[0].charAt(0).toLowerCase()}${p.objectives[0].slice(1)}`
  }
  if (d.tier === 'honors') {
    questions += `\n${numbered + 1}. **Constructed response:** ${p.extension}`
    key += '\n- Constructed response: score with the 4-level rubric'
  }
  return [
    {
      id: 'objective',
      title: 'Objective',
      body: `This ${count}-item quiz checks whether ${learners(levelOf(d), d.grade)} can:\n- ${p.objectives[0]}\n- ${p.objectives[1]}`,
    },
    {
      id: 'directions',
      title: 'Directions',
      body: `- Read each question carefully and choose the best answer\n- Shade the letter of your answer on the answer sheet\n- Time limit: ${time} minutes`,
    },
    { id: 'questions', title: 'Questions', body: questions },
    { id: 'key', title: 'Answer Key', body: key },
  ]
}

function rubricSections(p: Pack, d: DraftParams): DraftSection[] {
  let criteria = p.criteria
  if (d.tier === 'remedial') criteria = criteria.slice(0, 3)
  if (d.tier === 'honors') criteria = [...criteria, ['Extension inquiry', p.extension]]
  const total = criteria.length * 4
  // DepEd cut-offs; a band too narrow to hold a whole score is skipped.
  const scoring = [`- Total: ${total} points (${criteria.length} criteria × 4 levels)`]
  let upper = total
  for (const [pct, label] of [
    [0.9, 'Outstanding'],
    [0.85, 'Very Satisfactory'],
    [0.8, 'Satisfactory'],
    [0.75, 'Fairly Satisfactory'],
  ] as const) {
    const lower = Math.ceil(total * pct)
    if (lower > upper) continue
    scoring.push(`- ${lower === upper ? lower : `${lower}–${upper}`}: ${label}`)
    upper = lower - 1
  }
  scoring.push(`- Below ${upper + 1}: Did Not Meet Expectations`)
  return [
    {
      id: 'objective',
      title: 'Learning Target',
      body: `${capitalizeFirst(learners(levelOf(d), d.grade))} will ${p.objectives[0].charAt(0).toLowerCase()}${p.objectives[0].slice(1)} and communicate their findings clearly.\n- **Task:** ${p.task}`,
    },
    { id: 'criteria', title: 'Criteria', body: criteria.map(([c, desc]) => `- **${c}:** ${desc}`).join('\n') },
    {
      id: 'levels',
      title: 'Performance Levels',
      body: [
        '- **4 · Exemplary:** Exceeds every criterion with precise, well-supported work',
        '- **3 · Proficient:** Meets each criterion with minor errors',
        '- **2 · Developing:** Meets some criteria; key ideas are incomplete',
        '- **1 · Beginning:** Shows limited evidence of understanding',
      ].join('\n'),
    },
    {
      id: 'scoring',
      title: 'Scoring Guide',
      body: scoring.join('\n'),
    },
  ]
}

export function generateDraft(params: DraftParams, createdISO = new Date().toISOString()): Draft {
  const pack = packFor(params.topic)
  const minutes = lessonMinutes(levelOf(params), params.grade)
  const sections =
    params.mode === 'lesson'
      ? lessonSections(pack, params, minutes)
      : params.mode === 'remedial'
        ? remedialSections(pack, params)
        : params.mode === 'quiz'
          ? quizSections(pack, params)
          : rubricSections(pack, params)
  return {
    ...params,
    id: `draft-${Date.parse(createdISO).toString(36)}`,
    title: `${MODES[params.mode].label}: ${params.topic.trim()}`,
    minutes,
    sections,
    refinements: [],
    createdISO,
    origin: 'template',
  }
}

/** Suggested starting objectives for a topic, one per line. */
export function suggestedObjectives(topic: string): string {
  return packFor(topic).objectives.slice(0, 2).join('\n')
}

const SIMPLE_WORDS: [string, string][] = [
  ['utilizes', 'uses'],
  ['utilized', 'used'],
  ['utilize', 'use'],
  ['demonstrates', 'shows'],
  ['demonstrate', 'show'],
  ['subsequently', 'then'],
  ['facilitate', 'lead'],
  ['approximately', 'about'],
  ['comprehend', 'understand'],
  ['illustrate', 'show'],
  ['analyze', 'study'],
  ['evaluate', 'judge'],
  ['determine', 'find'],
  ['construct', 'build'],
  ['converts', 'changes'],
  ['continuous', 'nonstop'],
  ['reactants', 'starting materials'],
  ['justify', 'explain'],
  ['annotate', 'mark up'],
  ['accurately', 'correctly'],
  ['independent and dependent variables', 'what you change and what you measure'],
]

export function simplifyText(text: string): string {
  let out = text
  for (const [from, to] of SIMPLE_WORDS) {
    out = out.replace(new RegExp(`\\b${from}\\b`, 'gi'), (match) =>
      match[0] === match[0].toUpperCase() ? to.charAt(0).toUpperCase() + to.slice(1) : to,
    )
  }
  return out
}

const TL: Record<string, { title: string; line: (topicTl: string) => string }> = {
  objective: { title: 'Layunin', line: (t) => `Sa pagtatapos ng aralin, maipapaliwanag ng mga mag-aaral ang ${t}.` },
  warmup: { title: 'Pagganyak', line: () => 'Sagutin ang tanong at ibahagi ang iyong hula sa iyong katabi.' },
  core: { title: 'Pangunahing Gawain', line: () => 'Gawin ang bawat istasyon kasama ang iyong pangkat at itala ang inyong mga obserbasyon.' },
  guided: { title: 'Ginabayang Pagsasanay', line: () => 'Sundan ang halimbawa nang hakbang-hakbang, saka sagutin ang mga pagsasanay.' },
  exit: { title: 'Pangwakas na Pagtataya', line: () => 'Sagutin nang maikli ang mga tanong bago lumabas ng silid-aralan.' },
  directions: { title: 'Panuto', line: () => 'Basahing mabuti ang bawat tanong at piliin ang pinakaangkop na sagot.' },
  questions: { title: 'Mga Tanong', line: () => 'Sagutin ang lahat ng tanong. Isulat ang titik ng tamang sagot.' },
  key: { title: 'Susi sa Pagwawasto', line: () => 'Gamitin ang susi sa pagwawasto upang suriin ang mga sagot.' },
  criteria: { title: 'Pamantayan', line: () => 'Ito ang mga pamantayang gagamitin sa pagmamarka ng inyong gawa.' },
  levels: { title: 'Antas ng Pagganap', line: () => 'Ang 4 ang pinakamataas na antas at ang 1 ang pinakamababa.' },
  scoring: { title: 'Gabay sa Pagmamarka', line: () => 'Pagsamahin ang puntos sa bawat pamantayan upang makuha ang kabuuang marka.' },
  review: { title: 'Mga Tanong sa Pagbabalik-aral', line: () => 'Sagutin ang tatlong tanong upang balikan ang aralin.' },
}

function bilingualSection(section: DraftSection, topicTl: string): DraftSection {
  const tl = TL[section.id]
  if (!tl) return section
  return {
    ...section,
    title: `${section.title} / ${tl.title}`,
    body: `${section.body}\n\n> Sa Filipino: ${tl.line(topicTl)}`,
  }
}

/** Applies a refinement to the current (possibly hand-edited) sections. */
export function applyRefinement(draft: Draft, refinement: Refinement): Draft {
  if (draft.refinements.includes(refinement)) return draft
  const pack = packFor(draft.topic)
  let sections = draft.sections
  if (refinement === 'review') {
    let added: DraftSection = {
      id: 'review',
      title: 'Review Questions',
      body: pack.review.map((q, i) => `${i + 1}. ${q}`).join('\n'),
    }
    if (draft.refinements.includes('simplify')) added = { ...added, body: simplifyText(added.body) }
    if (draft.refinements.includes('bilingual')) added = bilingualSection(added, pack.topicTl)
    sections = [...sections, added]
  } else if (refinement === 'simplify') {
    sections = sections.map((s) => ({ ...s, body: simplifyText(s.body) }))
  } else {
    sections = sections.map((s) => bilingualSection(s, pack.topicTl))
  }
  return { ...draft, sections, refinements: [...draft.refinements, refinement] }
}

function metaLine(draft: Draft): string {
  return `${gradeLabel(levelOf(draft), draft.grade)} · ${draft.subject} · ${TIERS[draft.tier].label} · ${draft.minutes} min`
}

export function draftToMarkdown(draft: Draft): string {
  const body = draft.sections.map((s) => `## ${s.title}\n\n${s.body}`).join('\n\n')
  return `# ${draft.title}\n\n_${metaLine(draft)}_\n\n${body}\n\n---\nGenerated with GabAI EDU · Edge AI\n`
}

function csvCell(value: string | number): string {
  const text = String(value)
  return /[",\n]/.test(text) ? `"${text.replace(/"/g, '""')}"` : text
}

export function draftToCsv(draft: Draft): string {
  const rows: (string | number)[][] = [['module', 'grade', 'section', 'order', 'content']]
  for (const section of draft.sections) {
    let order = 0
    for (const block of parseBlocks(section.body)) {
      const lines = 'items' in block ? block.items.map((i) => [i.text, ...i.sub].join(' — ')) : [block.text]
      for (const line of lines) {
        order += 1
        rows.push([draft.title, gradeLabel(levelOf(draft), draft.grade), section.title, order, stripInline(line)])
      }
    }
  }
  return rows.map((r) => r.map(csvCell).join(',')).join('\n') + '\n'
}

export function draftToHtml(draft: Draft): string {
  const esc = (t: string) => t.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
  const sections = draft.sections
    .map((s) => `<section><h2>${esc(s.title)}</h2>${blocksToHtml(parseBlocks(s.body))}</section>`)
    .join('')
  return `<!doctype html><html><head><meta charset="utf-8"><title>${esc(draft.title)}</title><style>
body{font-family:Helvetica,Arial,sans-serif;color:#1a1a1a;margin:32px;line-height:1.5;font-size:13px}
header{border:2px solid #1a1a1a;border-radius:12px;padding:16px 18px;margin-bottom:18px;background:#fff7d1}
h1{font-size:20px;margin:0 0 4px}.meta{font-family:monospace;font-size:11px;letter-spacing:.04em;text-transform:uppercase}
h2{font-size:15px;border-bottom:2px solid #1a1a1a;padding-bottom:4px;margin:20px 0 8px}
ul,ol{padding-left:20px;margin:6px 0}li{margin:3px 0}.sub{color:#444}
.note{border-left:4px solid #6bcb77;background:#effaf0;padding:6px 10px;margin:8px 0}
footer{margin-top:28px;font-family:monospace;font-size:10px;color:#555}section{break-inside:avoid}
</style></head><body><header><h1>${esc(draft.title)}</h1><div class="meta">${esc(metaLine(draft))}</div></header>${sections}<footer>Generated with GabAI EDU · Edge AI</footer></body></html>`
}

export function slugify(text: string): string {
  return (
    text
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-|-$/g, '')
      .slice(0, 60) || 'gabai-module'
  )
}
